server:
  port: 8080
#  tomcat:
#    max-threads: 500
#    uri-encoding: UTF-8
#    accesslog:
#      enabled: true
#      directory: /data/logs
#      rotate: true
#      pattern: '%h %l %u %t "%r" %s %b %D'

spring:
  application:
    name: demo
  profiles:
    active: local

---
spring:
  profiles: local

---
spring:
  profiles: docker